# Generated by Django 2.1.15 on 2020-05-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LifePlanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'status'},
        ),
    ]
