# Generated by Django 2.1.15 on 2020-05-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LifePlanner', '0002_auto_20200503_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
    ]
